### ISSUE TITLE
This will no longer work with the Particle Dev IDE unless you flatten the directory tree

### ISSUE THREAD

**Issue by moeburn** [vshymanskyy/blynk-library-spark#10]
Your code is trying to include files in a tree structure, like this:

`#include "Blynk/BlynkProtocol.h"`

Particle doesn't allow that.  All libraries that you want to include _must_ be in a flat directory structure alongside the ino file.  No directories allowed.  I had to copy all the files from the subfolder, move it to the main folder, and then delete all references to _Blynk/_ in every single library just to get it to compile.

**Comment by monkbroc** [comment]
Can you give details about your OS, dev tool used (Web IDE, Desktop IDE or CLI)? Particle libraries and projects support nested directories so I'm interested to know where you see this issue.

**Comment by vshymanskyy** [comment]
This is no longer true. Particle now uses 2.0 library format. If you still have issues, please contact particle or reopen issue bere.
