### ISSUE TITLE
there are no arguments to 'ntohs' that depend on a template parameter, so a declaration of 'ntohs' must be available [-fpermissive]

### ISSUE THREAD

**Issue by rainierez** [vshymanskyy/blynk-library-spark#2]
Veryfing code using this library in Particle Build fails with this error:
```
blynk/BlynkProtocol.h:250:34: error: there are no arguments to 'ntohs' that depend on a template parameter, so a declaration of 'ntohs' must be available [-fpermissive]
     hdr.msg_id = ntohs(hdr.msg_id)

**Comment by vshymanskyy** [comment]
Sorry, was fixed long time ago

**Comment by SmartSouth** [comment]
If it's fixed, why do I still get this error? The Particle example in the Blynk library throws 8 error messages. So if it's fixed, what am I doing wrong?

**Comment by vshymanskyy** [comment]
You have to get sure you're using Blynk library v0.3.3 or later.
What hardware are you using? please be more specific.
