### ISSUE TITLE
there are no arguments to 'ntohs' that depend on a template parameter, so a declaration of 'ntohs' must be available [-fpermissive] 

### ISSUE THREAD

**Issue by SmartSouth** [vshymanskyy/blynk-library-spark#4]
Any ideas what I'm doing wrong?

**Comment by vshymanskyy** [comment]
Duplicate issue

**Comment by vshymanskyy** [comment]
You have to get sure you're using Blynk library v0.3.3 or later.
What hardware are you using? please be more specific.

**Comment by cabelee** [comment]
i am using the latest version 0.3.10 and getting this issure?

**Comment by vshymanskyy** [comment]
What hardware do you use?

**Comment by cabelee** [comment]
particle photon using with an iphone  tying to add the librarie though the web ide

**Comment by cabelee** [comment]
particle photon using with an iphone tying to add the librarie though the web ide 
----- Original Message -----

**Comment by cabelee** [comment]
using photon with iphone tying to add the libraries with the web ide

**Comment by cabelee** [comment]
updated device firmware working now not sure if that was problem thanks for responding so quickly
