### ISSUE TITLE
Particle Core: When using BLYNK_CONNECTED or Blynk.connected(), Particle Core Flashes red and reboots

### ISSUE THREAD

**Issue by justbill2020** [vshymanskyy/blynk-library-spark#6]
Anytime my code uses BLYNK_CONNECTED to run code after initial connection or I check if connected using Blynk.connected() my Particle Core starts flashing red and then restarts... please advise... 

Particle firmware 0.5.2 and Blynk version 0.3.8...

**Comment by justbill2020** [comment]
additional testing show same issue after removing all reference to BLYNK_CONNECTED or Blynk.connected()... removed Blynk.syncAll()... this kept Particle Core from flashing red...

**Comment by rgm3** [comment]
I had the same problem when using the Particle Timer class:
```
Timer bpTimer(3000L, blynkPublish);
bpTimer.start();
void blynkPublish() { Blynk.virtualWrite(V0, "something"); }
```
I refactored to check elapsed millis() to avoid the issue.

**Comment by vshymanskyy** [comment]
I just checked, and this works for me.
Also, Particle Timer should not be used for calling Blynk functions - please read example comments carefully. Closing for now, please open new issue if you still have troubles.
