### ISSUE TITLE
Particle Electron Compile Error- can't find WidgetGPS.h

### ISSUE THREAD

**Issue by csoulakian** [vshymanskyy/blynk-library-spark#7]
I'm trying to compile for the Particle Electron and I get the error that it can't find WidgetGPS.h. When I try commenting out that include line in BlynkWidgets.h, it says `"BLYNK_ALREADY_LOGGED_IN was not declared in this scope.`

I'm using Particle Dev (the local IDE based on Atom) and I know it's not an issue with my IDE setup because version 0.3.10 of Blynk works on Particle Dev.

**Comment by IOThingExplorer** [comment]
Same problem. Should I be using this repository or the Arduino one for the Particle Photon?
Thanks.

**Comment by IOThingExplorer** [comment]
Solution: 
1) Go back one version folder in GitHub.
2) Convert the parameter to string: virtualRead(V5, String(x));

**Comment by legoadk** [comment]
Better solution:

Copy src/WidgetGPS.h and src/Blynk/BlynkProtocol.h from upstream 0.4.0 release: https://github.com/blynkkk/blynk-library/releases/tag/v0.4.0

(you may still need #2 on your list)

**Comment by danielmapar** [comment]
That did the job @legoadk. Also remember to update those files with the appropriate header path:

Rather than <Blykn/...>, just do "Blink...h"

No need for a global header search in this case

**Comment by csoulakian** [comment]
The most recent update (still version 0.4.0) fixed the compile error. Thanks!
